version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: rahuroi-pg
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: rahuroi
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
